# CodeRabbit Configuration for PMPulse
# https://docs.coderabbit.ai/reference/configuration

language: "en-US"
tone_instructions: "Be direct and concise. Focus on security, performance, and Laravel/React best practices."
early_access: false
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: false
  abort_on_close: true

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - main

  # Path-specific review instructions
  path_instructions:
    - path: "app/Services/**"
      instructions: |
        Focus on:
        - Business logic correctness
        - Proper use of dependency injection (not facades)
        - Error handling and retry logic for API calls
        - Idempotent operations using updateOrCreate()
        - No multi-tenancy patterns or tenant_id fields

    - path: "app/Http/Controllers/**"
      instructions: |
        Ensure controllers are thin. Business logic should be in Service classes.
        Verify proper Form Request validation is used.

    - path: "app/Models/**"
      instructions: |
        Check for:
        - Proper use of external_id for AppFolio identifiers
        - Eloquent scopes for reusable queries
        - Proper relationship definitions

    - path: "database/migrations/**"
      instructions: |
        Verify:
        - snake_case column naming
        - Proper indexing on foreign keys and WHERE clause columns
        - No tenant_id or multi-tenancy fields
        - external_id columns for AppFolio data

    - path: "resources/js/**"
      instructions: |
        Check for:
        - Functional components with hooks only
        - Tailwind CSS usage (no inline styles)
        - Proper Inertia.js patterns
        - Recharts for data visualization

    - path: "app/Notifications/**"
      instructions: |
        CRITICAL: Email copy must NOT contain hyphens. Flag any hyphen usage in notification text.

  # Files to exclude from review
  path_filters:
    - "!**/*.lock"
    - "!package-lock.json"
    - "!composer.lock"
    - "!public/build/**"
    - "!bootstrap/cache/**"
    - "!storage/**"
    - "!vendor/**"
    - "!node_modules/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!.DS_Store"

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: "local"
  pull_requests:
    scope: "local"

code_generation:
  docstrings:
    language: "en-US"
